name: My Flutter Workflow

on: 
  push: 
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze my code and run linting tests
        run: flutter analyze

      - name: Run my unit tests
        run: flutter test

      - name: Build a release APK for my app
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          